version: '3.9'
services:
  db:
    build: ./db
    volumes:
      - data:/data/db
    restart: on-failure:5
    ports:
      - '${MONGO_PORT}:${MONGO_PORT}'
    env_file:
      - './.env'
    command: 'mongod --port ${MONGO_PORT} --bind_ip_all'
  server:
    build:
      context: ./
    volumes:
      - ./log:/app/log
      - ./:/app/
    depends_on:
      - db
    restart: on-failure:5
    ports:
      - '${PORT}:${PORT}'
    env_file:
      - './.env'
networks:
  default:
    name: test-express
volumes:
  data:
    external: true
